export interface BoardLineItem {
  placement: number;
  song: string;
  artist: string;
}

export interface Board {
  name: string;
  lines: Array<BoardLineItem>;
};

export const songlistDrugs: Board = {
  name: 'Flying High - Die 100 besten Drogen-Lieder',
  lines: [
    { placement: 1, song: "Heroin", artist: "The Velvet Underground" },
    { placement: 2, song: "White Rabbit", artist: "Jefferson Airplaine" },
    { placement: 3, song: "The Drugs Don't Work", artist: "The Verve" },
    { placement: 4, song: "Rehab", artist: "Amy Winehouse" },
    { placement: 5, song: "I´m Waiting For The Man", artist: "The Velvet Undergound" },
    { placement: 6, song: "Lucy In The Sky With Diamonds", artist: "The Beatles" },
    { placement: 7, song: "The Needle And The Damage Done", artist: "Neil Young" },
    { placement: 8, song: "Feel Good Hit Of The Summer", artist: "Queens Of The Stone Age" },
    { placement: 9, song: "Purple Haze", artist: "The Jimi Hendrix Experience" },
    { placement: 10, song: "Under The Bridge", artist: "Red Hot Chili Peppers" },
    { placement: 11, song: "Golden Brown", artist: "The Stranglers" },
    { placement: 12, song: "Cocaine", artist: "J. J. Cale" },
    { placement: 13, song: "Drogen Nehmen Und Rumfahren", artist: "Die Zukunft" },
    { placement: 14, song: "Am Tag, Als Conny Kramer Starb", artist: "Juliane Werding" },
    { placement: 15, song: "Needle In The Hay", artist: "Elliott Smith" },
    { placement: 16, song: "White Lines (Don't Don't Do It)", artist: "Grandmaster Flash & Melle Mel" },
    { placement: 17, song: "Pusherman", artist: "Curtis Mayfield" },
    { placement: 18, song: "Cold Turkey", artist: "John Lennon & Plastic Ono Band" },
    { placement: 19, song: "Sister Morphine", artist: "The Rolling Stones" },
    { placement: 20, song: "Comfortably Numb", artist: "Pink Floyd" },
    { placement: 21, song: "Eight Miles High", artist: "The Byrds" },
    { placement: 22, song: "Alkohol", artist: "Herbert Grönemeyer" },
    { placement: 23, song: "Lithium", artist: "Nirvana" },
    { placement: 24, song: "True Faith", artist: "New Order" },
    { placement: 25, song: "You Need The Drugs", artist: "Westbam feat. Richard Butler" },
    { placement: 26, song: "Gold Dust Woman", artist: "Fleetwood Mac" },
    { placement: 27, song: "Beetlebum", artist: "Blur" },
    { placement: 28, song: "Can't Feel My Face", artist: "The Weeknd" },
    { placement: 29, song: "Because I Got High", artist: "Afroman" },
    { placement: 30, song: "Hits From The Bong", artist: "Cypress Hill" },
    { placement: 31, song: "I Wanna Be Sedated", artist: "Ramones" },
    { placement: 32, song: "Cocaine In My Brain", artist: "Dillinger" },
    { placement: 33, song: "Where Is My Mind?", artist: "Pixies" },
    { placement: 34, song: "Higher Than The Sun", artist: "Primal Scream" },
    { placement: 35, song: "Sister Morphine", artist: "Marianne Faithfull" },
    { placement: 36, song: "Sorted For E's And Wizz", artist: "Pulp" },
    { placement: 37, song: "Champagne Supernova", artist: "Oasis" },
    { placement: 38, song: "Insane In The Brain", artist: "Cypress Hill" },
    { placement: 39, song: "Perfect Day", artist: "Lou Reed" },
    { placement: 40, song: "Mother I’ve Taken LSD", artist: "The Flaming Lips" },
    { placement: 41, song: "Straight Edge", artist: "Minor Threat" },
    { placement: 42, song: "Sex & Drugs & Rock & Roll", artist: "Ian Dury" },
    { placement: 43, song: "Hurt", artist: "Nine Inch Nails" },
    { placement: 44, song: "Mary Jane's Last Dance", artist: "Tom Petty & The Heartbreakers" },
    { placement: 45, song: "My Friend Jack", artist: "The Smoke" },
    { placement: 46, song: "Mother's Little Helper", artist: "The Rolling Stones" },
    { placement: 47, song: "Ebeneezer Goode", artist: "The Shamen" },
    { placement: 48, song: "Never Let Me Down Again", artist: "Depeche Mode" },
    { placement: 49, song: "Ganz Wien", artist: "Falco" },
    { placement: 50, song: "3 Tage Wach", artist: "Lützenkirchen" },
    { placement: 51, song: "Master Of Puppets", artist: "Metallica" },
    { placement: 52, song: "Bianco", artist: "Yung Hurn & RIN" },
    { placement: 53, song: "Cigarettes & Alcohol", artist: "Oasis" },
    { placement: 54, song: "Just One Fix", artist: "Ministry" },
    { placement: 55, song: "The Pusher", artist: "Steppenwolf" },
    { placement: 56, song: "Drugs", artist: "Upsahl" },
    { placement: 57, song: "Mutter, Der Mann Mit Dem Koks Ist Da", artist: "Falco" },
    { placement: 58, song: "Special K", artist: "Placebo" },
    { placement: 59, song: "Swimming Pools (Drank)", artist: "Kendrick Lamar" },
    { placement: 60, song: "Heute Schütte Ich Mich Zu", artist: "Karl Dall" },
    { placement: 61, song: "Eight Miles High", artist: "Hüsker Dü" },
    { placement: 62, song: "High By The Beach", artist: "Lana Del Rey" },
    { placement: 63, song: "My Drug Buddy", artist: "The Lemonheads" },
    { placement: 64, song: "Brown Sugar", artist: "The Rolling Stones" },
    { placement: 65, song: "Hurt", artist: "Johnny Cash" },
    { placement: 66, song: "White Punks On Dope", artist: "The Tubes" },
    { placement: 67, song: "Cola-Wodka", artist: "Holger Biege" },
    { placement: 68, song: "Alabama Song (Whisky Bar)", artist: "The Doors" },
    { placement: 69, song: "Why’d You Only Call Me When You’re High?", artist: "Arctic Monkeys" },
    { placement: 70, song: "I'm Your Pusher", artist: "Ice-T" },
    { placement: 71, song: "Hash Pipe", artist: "Weezer" },
    { placement: 72, song: "Brown Sugar", artist: "D'Angelo" },
    { placement: 73, song: "Tag Am Meer", artist: "Die Fantastischen Vier" },
    { placement: 74, song: "Sugar Man", artist: "Rodriguez" },
    { placement: 75, song: "Mix Mir Einen Drink", artist: "Feeling B" },
    { placement: 76, song: "Mary Jane", artist: "Rick James" },
    { placement: 77, song: "Bongzimmer", artist: "SXTN" },
    { placement: 78, song: "Crystal Meth In Brandenburg", artist: "Grim104" },
    { placement: 79, song: "Hotel California", artist: "Eagles" },
    { placement: 80, song: "Cocaine", artist: "Eric Clapton" },
    { placement: 81, song: "Willst Du", artist: "Alligatoah" },
    { placement: 82, song: "Needle Of Death", artist: "Bert Jansch" },
    { placement: 83, song: "Kokain", artist: "Hannes Wader" },
    { placement: 84, song: "I Got 5 On It", artist: "Luniz" },
    { placement: 85, song: "Rainy Day Women #12 & 35", artist: "Bob Dylan" },
    { placement: 86, song: "Karlsquell", artist: "Slime" },
    { placement: 87, song: "Xanny", artist: "Billie Eilish" },
    { placement: 88, song: "Ashes To Ashes", artist: "David Bowie" },
    { placement: 89, song: "White Horse", artist: "Laid Back" },
    { placement: 90, song: "We Are All On Drugs", artist: "Weezer" },
    { placement: 91, song: "Not If You Were The Last Junkie On Earth", artist: "The Dandy Warhols" },
    { placement: 92, song: "Pass That Dutch", artist: "Missy Elliott" },
    { placement: 93, song: "Lost", artist: "Frank Ocean" },
    { placement: 94, song: "Blinded By The Lights", artist: "The Streets" },
    { placement: 95, song: "Sam Stone", artist: "John Prine" },
    { placement: 96, song: "Nicotine", artist: "Chef'Special" },
    { placement: 97, song: "Novacane", artist: "Frank Ocean" },
    { placement: 98, song: "Strychnine", artist: "The Sonics" },
    { placement: 99, song: "King Heroin", artist: "James Brown" },
    { placement: 100, song: "Zeit Steht", artist: "Trettmann feat. Alli Neumann" },
  ]
};