import { Board } from "./lists";

export const top100Rock: Board = {
    name: 'Top100Rock',
    lines: [
    {placement: 1, artist: 'Black Sabbath', song: 'Paranoid'},
     {placement: 2, artist: 'Motörhead', song: 'Ace Of Spades'},
     {placement: 3, artist: 'Led Zeppelin', song: 'Kashmir'},
     {placement: 4, artist: 'Metallica', song: 'Enter Sandman'},
     {placement: 5, artist: 'AC/DC', song: 'Highway To Hell'},
     {placement: 6, artist: 'System Of A Down', song: 'Chop Suey!'},
     {placement: 7, artist: 'Metallica', song: 'Master Of Puppets'},
     {placement: 8, artist: "Guns N' Roses", song: 'Welcome To The Jungle'},
     {placement: 9, artist: 'Slayer', song: 'Raining Blood'},
     {placement: 10, artist: 'Rage Against The Machine', song: 'Killing In The Name'},
     {placement: 11, artist: 'Iron Maiden', song: 'The Number Of The Beast'},
     {placement: 12, artist: "Guns N' Roses", song: 'Paradise City'},
     {placement: 13, artist: 'The Beatles', song: 'Helter Skelter'},
     {placement: 14, artist: 'AC/DC', song: 'Thunderstruck'},
     {placement: 15, artist: 'Black Sabbath', song: 'War Pigs'},
     {placement: 16, artist: 'AC/DC', song: 'Let There Be Rock'},
     {placement: 17, artist: 'Deep Purple', song: 'Smoke On The Water'},
     {placement: 18, artist: 'Led Zeppelin', song: 'Whole Lotta Love'},
     {placement: 19, artist: 'Deep Purple', song: 'Child In Time'},
     {placement: 20, artist: 'AC/DC', song: 'T.N.T.'},
     {placement: 21, artist: 'Foo Fighters', song: 'The Pretender'},
     {placement: 22, artist: 'AC/DC', song: 'Back In Black'},
     {placement: 23, artist: 'The Runaways', song: 'Cherry Bomb'},
     {placement: 24, artist: 'MC5', song: 'Kick Out The Jams'},
     {placement: 25, artist: 'Helmet', song: 'Unsung'},
     {placement: 26, artist: 'Led Zeppelin', song: 'Black Dog'},
     {placement: 27, artist: 'Slayer', song: 'South Of Heaven'},
     {placement: 28, artist: 'Judas Priest', song: 'Breaking The Law'},
     {placement: 29, artist: 'AC/DC', song: 'Hells Bells'},
     {placement: 30, artist: 'Kiss', song: "I Was Made For Lovin' You"},
     {placement: 31, artist: 'The Kinks', song: 'You Really Got Me'},
     {placement: 32, artist: 'Danzig', song: 'Mother'},
     {placement: 33, artist: 'AC/DC', song: 'You Shook Me All Night Long'},
     {placement: 34, artist: 'L7', song: "Pretend We're Dead"},
     {placement: 35, artist: 'Beastie Boys', song: 'Sabotage'},
     {placement: 36, artist: 'Black Sabbath', song: 'Iron Man'},
     {placement: 37, artist: 'Metallica', song: 'One'},
     {placement: 38, artist: 'Thin Lizzy', song: 'The Boys Are Back In Town'},
     {placement: 39, artist: 'Ministry', song: 'Jesus Built My Hotrod'},
     {placement: 40, artist: 'Faith No More', song: 'Epic'},
     {placement: 41, artist: 'Judas Priest', song: 'Painkiller'},
     {placement: 42, artist: 'The Jimi Hendrix Experience', song: 'Purple Haze'},
     {placement: 43, artist: 'Ram Jam', song: 'Black Betty'},
     {placement: 44, artist: 'Soundgarden', song: 'Jesus Christ Pose'},
     {placement: 45, artist: 'Venom', song: 'Black Metal'},
     {placement: 46, artist: 'Twisted Sister', song: "We're Not Gonna Take It"},
     {placement: 47, artist: 'Metallica', song: 'Nothing Else Matters'},
     {placement: 48, artist: 'Iron Maiden', song: 'Hallowed Be Thy Name'},
     {placement: 49, artist: 'Rose Tattoo', song: 'Nice Boys'},
     {placement: 50, artist: 'Sepultura', song: 'Refuse Resist'},
     {placement: 51, artist: 'Led Zeppelin', song: 'Stairway To Heaven'},
     {placement: 52, artist: 'Motörhead', song: '(We Are) The Roadcrew'},
     {placement: 53, artist: 'Korn', song: 'Freak On A Leash'},
     {placement: 54, artist: "Guns N' Roses", song: 'November Rain'},
     {placement: 55, artist: 'Rainbow', song: 'Stargazer'},
     {placement: 56, artist: 'Black Sabbath', song: 'Black Sabbath'},
     {placement: 57, artist: 'Deftones', song: 'Change (In The House Of Flies)'},
     {placement: 58, artist: 'Metallica', song: 'Seek & Destroy'},
     {placement: 59, artist: 'Suicidal Tendencies', song: "You Can't Bring Me Down"},
     {placement: 60, artist: 'Anthrax', song: 'Antisocial'},
     {placement: 61, artist: 'Led Zeppelin', song: 'Immigrant Song'},
     {placement: 62, artist: 'Black Sabbath', song: 'Sabbath Bloody Sabbath'},
     {placement: 63, artist: 'Tool', song: 'Stinkfist'},
     {placement: 64, artist: 'The Donnas', song: 'Take It Off'},
     {placement: 65, artist: 'AC/DC', song: 'Whole Lotta Rosie'},
     {placement: 66, artist: 'Deep Purple', song: 'Highway Star'},
     {placement: 67, artist: 'Heart', song: 'Barracuda'},
     {placement: 68, artist: 'Bon Jovi', song: "Livin' On A Prayer"},
     {placement: 69, artist: 'Deep Purple', song: 'Black Night'},
     {placement: 70, artist: 'Deep Purple', song: 'Speed King'},
     {placement: 71, artist: 'UFO', song: 'Boogie For George'},
     {placement: 72, artist: 'The Jimi Hendrix Experience', song: 'Voodoo Child'},
     {placement: 73, artist: 'Dio', song: 'Holy Diver'},
     {placement: 74, artist: 'Blue Öyster Cult', song: "(Don't Fear) The Reaper"},
     {placement: 75, artist: 'Boston', song: 'More Than A Feeling'},
     {placement: 76, artist: 'Monster Magnet', song: 'Space Lord'},
     {placement: 77, artist: 'Type O Negative', song: 'Everything Dies'},
     {placement: 78, artist: 'Deep Purple', song: 'Fireball'},
     {placement: 79, artist: 'Napalm Death', song: 'You Suffer'},
     {placement: 80, artist: 'Metallica', song: 'Hit The Lights'},
     {placement: 81, artist: 'The Cult', song: 'She Sells Sanctuary'},
     {placement: 82, artist: 'Steppenwolf', song: 'Born To Be Wild'},
     {placement: 83, artist: 'The Who', song: 'My Generation'},
     {placement: 84, artist: 'Tool', song: 'Sober'},
     {placement: 85, artist: 'Sunn O)))', song: 'It Took The Night To Believe'},
     {placement: 86, artist: 'Leather Nun', song: 'No Rule'},
     {placement: 87, artist: 'Kiss', song: 'Rock And Roll All Nite'},
     {placement: 88, artist: 'Tool', song: 'Schism'},
     {placement: 89, artist: 'Whitesnake', song: 'Here I Go Again'},
     {placement: 90, artist: 'Alice Cooper', song: 'Poison'},
     {placement: 91, artist: 'The Jimi Hendrix Experience', song: 'All Along The Watchtower'},
     {placement: 92, artist: 'Deep Purple', song: 'Hush'},
     {placement: 93, artist: 'Kiss', song: 'Detroit Rock City'},
     {placement: 94, artist: 'The Darkness', song: 'I Believe In A Thing Called Love'},
     {placement: 95, artist: 'Foo Fighters', song: 'All My Life'},
     {placement: 96, artist: 'Queen', song: 'Bohemian Rhapsody'},
     {placement: 97, artist: 'D-A-D', song: 'Sleeping My Day Away'},
     {placement: 98, artist: 'Van Halen', song: "Ain't Talkin 'Bout Love"},
     {placement: 99, artist: 'Pantera', song: 'Walk'},
     {placement: 100, artist: 'UFO', song: 'Prince Kajuku'},
    ]
}